### ISSUE TITLE
Extend image-exec events with username (e.g. getpwuid)

### ISSUE THREAD

**Issue by losandros** [droe/xnumon#28]
Hi

I'm currently working on a mapping for Sysmon EventCode 1 within Splunk so that you can easily just search for:
- Username
- Image CWD
- Image Path
- Image Executable
- Image Hash
- ParentImage CWD
- ParentImage Path
- ParentImage Executable
- ParentImage Hash

More or less everything is already there but I miss the username. Currently there are auid, euid and uid available. An extensions to get the ausername, eusername and username should be possible by using the getpwuid() function (like described here: https://www.unix.com/man-page/osx/3/getpwuid/ )

This would help having a common search interface within Splunk or other SIEM products to search for the same "indicator".

**Comment by losandros** [comment]
Ah, just saw that this is already in your roadmap as feature #4

**Comment by droe** [comment]
Thanks for the feature request, I've scheduled #4 for the next release.
