### ISSUE TITLE
Apply my own configration.plist error!

### ISSUE THREAD

**Issue by MrJeffyw** [droe/xnumon#48]
I have copied my own configration.plist to /Library/Application Support/ch.roe.xnumon/configration.plist. But when i run "xnumonctl restart",it still loaded the default configration! 

{"version":6,"time":"2018-11-26T07:17:22.364646000Z","eventcode":0,"op":"stop","build":{"version":"0.1.7.1","date":"2018-11-08","info":"V:GIT"},"config":{"path":"/Library/Application Support/ch.roe.xnumon/configuration.plist-default","id":"default-0.1.7.1","launchd_mode":true,"debug":false,"events":"0,1,2,3,4","stats_interval":3600,"kextlevel":"hash","hashes":"sha256","codesign":true,"envlevel":"dyld","resolve_users_groups":true,"omit_mode":false,"omit_size":false,"omit_mtime":false,"omit_ctime":false,"omit_btime":false,"omit_sid":false,"omit_groups":false,"omit_apple_hashes":true,"ancestors":"unlimited","logdst":"file","logfmt":"json","logoneline":true,"logfile":"/var/log/xnumon.log","limit_nofile":8192,"suppress_image_exec_at_start":true,"suppress_image_exec_by_ident":3,"suppress_image_exec_by_path":1,"suppress_image_exec_by_ancestor_ident":0,"suppress_image_exec_by_ancestor_path":1,"suppress_process_access_by_subject_ident":4,"suppress_process_access_by_subject_path":0},"system":{"name":"Mac OS X","version":"10.13.6","build":"17G65"}}

**Comment by MrJeffyw** [comment]
@droe

**Comment by MrJeffyw** [comment]
When i enable debug,i got this:
xnumon 0.1.7.1 (built 2018-11-08)
Copyright (c) 2017-2018, Daniel Roethlisberger <daniel@roe.ch>
https://www.roe.ch/xnumon
Build info: V:GIT
Kernel extension protocol version: 1
Log event version: 6
Available log formats are: json json-seq yaml xml
Available log destinations are: file - syslog
Loading configuration:
	config_id               ITSec-__BUILD_VERSION__
	log_format              json
	log_destination         /var/log/xnumon.log
	hashes                  md5,sha256
	events                  0,1,2,3,4,5,6,7
Failed to load 'events'
Failed to load configuration!
Fatal error, exiting

**Comment by droe** [comment]
Events 5 to 7 are not supported by xnumon 0.1.7.1. You are using a configuration from the `develop` branch with a release binary. Use the configuration file installed by the release as a template, not the one in the `develop` branch in git.

**Comment by MrJeffyw** [comment]
how can i log events 5 to 7
